In [2]:
import matplotlib.pyplot as plt
import matplotlib as mp
from matplotlib.cm import jet_r
import scipy.io as sio
import numpy as np

In [3]:
file_path = '../tests/data/openep_dataset_1.mat'

In [4]:
data_tri_X_lst = []
data_tri_T_lst = []
x_values = []
y_values = []
z_values = []
minval=0
maxval=1

col_map=jet_r

default_color = 'gray'
# Magenta - RGBA array
magenta = np.array([255/255, 0/255, 255/255, 1])
below_color=(0/255, 0/255, 0/255, 255/255)
above_color=(255/255, 0/255, 255/255, 255/255)
nan_color=(50/255, 50/255, 50/255, 255/255)
sample_color = (255/255, 0/255, 0/255, 1/255)


In [5]:
main_file = sio.loadmat(file_path)

In [12]:
# Vertices/Points = .X
data_tri_X = main_file['userdata']['surface_triRep_X'][0][0]
x = data_tri_X[:,0]
y = data_tri_X[:,1]
z = data_tri_X[:,2]

# Triangulation/faces - .T
data_tri_T = main_file['userdata']['surface_triRep_Triangulation'][0][0]
# Resolving indexing issue - matlab to python
t = data_tri_T-1

# Voltage Data
data_act_bip = main_file['userdata']['surface'][0][0]['act_bip'][0][0]
voltage_data = data_act_bip[:,1]
voltage_new = np.reshape(a=voltage_data,newshape=(len(voltage_data),1))
print(voltage_new.shape)
color = np.mean(voltage_new[t], axis=1)
print('color',color.shape)

# ColorShell
# coloring the shell by the voltage value rather than z-axis height
min_volt = min(voltage_new)
max_volt = max(voltage_new)
print('min_volt',min_volt)


# # size_cm = np.diff([maxval,minval])
# size_cm = maxval-minval
# print('size-cm',size_cm)

# size_below_threshold = abs(minval-min_volt)
# size_between_threshold = maxval-minval
# size_above_threshold = max_volt


# print('size_below_threshold',size_below_threshold)
# print('size_between_threshold',size_between_threshold)
# print('size_above_threshold',size_above_threshold)




# cm_jet = plt.cm.get_cmap('jet_r',size_cm) 
# # print(len(cm_jet))
# col_map = cm_jet(np.linspace(0,1,size_cm*256))
# print(col_map.shape)


field = voltage_new
new_field = np.zeros((field.shape[0], 4), np.int32)

for idx in range(len(field)):
#     print('idx',idx)
    val = field[idx]

    if np.isnan(val):
        col = nan_color
    elif val < minval:
        col = below_color
    elif val > maxval:
        col = above_color
    else:
        valscaled = (val - minval) / (maxval - minval)
        col = col_map(valscaled)

        if isinstance(col[0],float):
            col=[int(c*255) for c in col]

    new_field[idx] = col

print(new_field.shape)

c = np.asarray(list(map(lambda x:x ,new_field)))
print(c)



(9279, 1)
color (10296, 1)
min_volt [0.069]
(9279, 4)
[[1 0 1 1]
 [0 0 0 1]
 [0 0 0 1]
 ...
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]]


In [10]:
# DRAW THE SURFACE
# Create a new fig window
fig = plt.figure(num=1,
                 figsize=[10,8],
                 facecolor='#F0F0F0',
                 # constrained_layout=True,
                 frameon=True,
                 tight_layout=False,
                 dpi=500)

# get the current 3d axis on the current fig
ax1 = fig.add_subplot(1,1,1, projection='3d')




    
# print(dir(ax1))
# Trisurface 3-D Mesh Plot
surf1 = ax1.plot_trisurf(x,
                         y,
                         z,
                         triangles=t,
                         linewidth=0.1,
                         antialiased=False,
                         color=c[0],
                         # cmap=newcmp,
                         shade=True,
#                          norm=norm
                         # Z=voltage_new
                         )

surf1.set_array(voltage_new)
# Trimesh - Set default azim and elev
ax1.view_init(elev=18,azim=37)


# Controls to Zoom Trimesh Plot
ax1.xaxis.zoom(2)
ax1.yaxis.zoom(2)
ax1.zaxis.zoom(2)

ax1.set_title('OpenEP TriRep Anatomy Data')
plt.axis('off')
plt.show()

/home/jra21/.local/lib/python3.6/site-packages/ipykernel_launcher.py:39: MatplotlibDeprecationWarning: 
The zoom function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
/home/jra21/.local/lib/python3.6/site-packages/ipykernel_launcher.py:40: MatplotlibDeprecationWarning: 
The zoom function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
/home/jra21/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: MatplotlibDeprecationWarning: 
The zoom function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.


ValueError: Collections can only map rank 1 arrays

<Figure size 5000x4000 with 1 Axes>

In [14]:
print(dir(surf1))

['_A', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_add_checker', '_agg_filter', '_alias_map', '_alpha', '_animated', '_antialiaseds', '_axes', '_bcast_lwls', '_capstyle', '_check_update', '_clipon', '_clippath', '_closed', '_codes3d', '_contains', '_default_contains', '_edge_default', '_edgecolor3d', '_edgecolors', '_edgecolors2d', '_facecolor3d', '_facecolors', '_facecolors2d', '_factor', '_get_clipping_extent_bbox', '_gid', '_hatch', '_hatch_color', '_in_layout', '_is_filled', '_is_stroked', '_joinstyle', '_label', '_linestyles', '_linewidths', '_mouseover', '_offset_position', '_offsets', '_offsetsNone', '_oid', '_original_edgecolor', '_original_facecolor', '_path_effect