In [1]:
import sys
sys.path.append('/home/jra21/work/source/repos/opep')

In [2]:
from openep import io as openep_io
from openep import case as openep_case
from openep import mesh_routines as openep_mesh
from openep import case_routines as case_routines
from openep import draw_routines as draw
import numpy as np

In [3]:
filename = '/home/jra21/work/source/repos/opep/examples/data/new_dataset_2.mat'
distance_thresh = 10

ep_case = openep_io.load_case(filename)

In [ ]:
# Anatomic descriptions (Mesh) - nodes and indices
pts = ep_case.nodes
indices = ep_case.indices


In [ ]:
# Electric data
# Locations – Cartesian co-ordinates, projected on to the surface 
locations = case_routines.get_electrogram_coordinates(ep_case,'type','bip')
i_egm = ep_case.electric['egm'].T
i_vp = case_routines.getMappingPointsWithinWoI(ep_case)
# macthing the shape of ivp with data
i_vp_egm = np.repeat(i_vp, repeats=i_egm.shape[1], axis=1)
# macthing the shape of ivp with coords
i_vp_locations = np.repeat(i_vp, repeats=locations.shape[1],axis=1)

# Replacing the values outside the window of interest with Nan values
i_egm[~i_vp_egm] = np.nan
locations[~i_vp_locations] = np.nan

# For each mapping point, n, find the voltage amplitude
max_volt = np.amax(a=i_egm,axis=1).reshape(len(i_egm),1)
min_volt = np.amin(a=i_egm,axis=1).reshape(len(i_egm),1)

amplitude_volt = np.subtract(max_volt,min_volt)

for indx in range(amplitude_volt.shape[1]):
    temp_data = amplitude_volt[:,indx]
    temp_coords = locations
    i_nan = np.isnan(temp_data)
    temp_data=temp_data[~i_nan]
    temp_coords=temp_coords[~i_nan]


    interp = case_routines.OpenEPDataInterpolator(method='rbf',distanceThreshold=distance_thresh,rbfConstant=1)
    vertex_voltage_data = interp.interpolate(x0=temp_coords,d0=temp_data,x1=pts)



vsurf = draw.DrawMap(ep_case,
        volt = vertex_voltage_data,
        freeboundary_color='black',
        cmap='jet_r',
        freeboundary_width=5,
        minval=0,
        maxval=2,
        volt_below_color='brown', 
        volt_above_color='magenta', 
        nan_color='gray', 
        plot=True,)

In [ ]:
# import numpy as np

# def get_electrogram_coordinates(mesh_case, *args):
#     '''
    
#     '''
#     n_standard_args = 1
#     v_type = "bip"
    
#     nargin = len(args)+1
#     if nargin>n_standard_args:
#         for i in range(0,(nargin-n_standard_args),2):
#             if np.char.lower(args[i]) == "type":
#                 v_type = args[i+1]
    
#     if np.char.lower(v_type) == "bip":
#         x = mesh_case.electric["egmX"].T
        
#     elif np.char.lower(v_type) == "uni":
#         if not("egmUniX" in mesh_case.electric):
#             raise ValueError("There is no unipolar data associated with this openep case")
            
#         else:
#             x = mesh_case.electric['egmUniX'].T
        
#     return x

In [ ]:
# Load EGM voltage values
# UseCase 28 - Get the electrogam at a mapping point #39

def get_egms_at_points(mesh_case,):
    pass

In [4]:
import numpy as np
hsurf1 = draw.getAnatomicalStructures(ep_case,plot=True)
py_length = np.array(hsurf1['Lengths'])
py_area = np.array(hsurf1['Area'])


mat_area = np.array([154.773515517340,260.175174080897,331.548738619316,508.782228060733,282.030461949226,949.773225470272,634.814247737892])
mat_length = np.array([48.4671072321950,66.1017537507639,67.9940320911940,82.9700863606623,63.4461422403505,120.374453837180,97.0835005157046])
for i in range(len(mat_length)):
    mat_length[i]=round(mat_length[i],4)

for j in range(len(mat_area)):
    mat_area[i]=round(mat_area[i],4)

diff_area = np.subtract(py_area,mat_area)`
print('difference-area:\n',diff_area)
diff_len = np.subtract(py_length,mat_length)
print('difference-length:\n',diff_len)

Perimeter is : 49.6852 | Area is: 154.8059
Perimeter is : 66.8485 | Area is: 260.2948
Perimeter is : 69.4603 | Area is: 331.543
Perimeter is : 84.9425 | Area is: 508.7591
Perimeter is : 65.7998 | Area is: 282.0847
Perimeter is : 122.2539 | Area is: 949.7754
Perimeter is : 98.9257 | Area is: 634.8818


ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

difference-area:
 [ 0.03238448  0.11962592 -0.00573862 -0.02312806  0.05423805  0.00217453
  0.0676    ]
difference-length:
 [1.2181 0.7467 1.4663 1.9724 2.3537 1.8794 1.8422]


In [5]:
import numpy as np

fb = [[14336, 14327],
       [14327, 14357],
       [14357, 14320]]
fb = np.array(fb)
print(fb[:,1])
print(fb[:,1][-1])

testset = np.array(list(np.zeros((fb.shape[0],fb.shape[1]))))
testset[:] = np.nan

testset[:,0] = fb[:,0]
print(testset)

# testset = [fb[:,1][-1], lambda x: for item in fb[1:len(fb-1)] ]


res = list(map(lambda x:x, fb[:,1][0:(len(fb)-1)]))
res.insert(0,fb[:,1][-1])
res = np.array(res)
print(res)

testset[:,1] = res
print('\n')
print(testset)

[14327 14357 14320]
14320
[[14336.    nan]
 [14327.    nan]
 [14357.    nan]]
[14320 14327 14357]


[[14336. 14320.]
 [14327. 14327.]
 [14357. 14357.]]
